# Generated by Django 3.1.1 on 2024-09-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField()),
                ('answer', models.IntegerField()),
            ],
        ),
    ]
